FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy only requirements.txt from root
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend source code into container
COPY backend/ /app

# Expose FastAPI port
EXPOSE 8100

# Start backend server
CMD ["uvicorn", "app.backend.'4. rag_pipeline'.main:app", "--reload", "--host", "0.0.0.0", "--port", "8100"]
