version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-clusterchat
    networks:
      - ollama-net
    volumes:
      - <your-ollama-path>/.ollama:/root/.ollama
    expose:
      - "11434"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8100:8100"
    env_file:
      - .env
    working_dir: /app
    networks:
      - ollama-net
    depends_on:
      - ollama

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:4173"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - ollama-net
    working_dir: /app
  
networks:
  ollama-net:
    driver: bridge