FROM node:20-alpine

WORKDIR /app

COPY app/package.json ./
COPY app/package-lock.json ./

RUN npm install

COPY .env .env

COPY /app .

RUN npm run build

EXPOSE 4173

CMD ["npm", "run", "preview", "--", "--host"]
