version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:4173"
    env_file:
      - .env
    depends_on:
      - backend
    working_dir: /app
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8100:8100"
    env_file:
      - .env
    working_dir: /app
